name = "Posits"
uuid = "206caa4e-a773-11ef-0a96-55713be7837f"
version = "0.2.0"
authors = ["Laslo Hunhold"]

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
libposit_jll = "51f2fc5f-9d5c-580b-98f8-9638c2091362"

[compat]
Random = "1.6.0"
julia = "1.6.7"
libposit_jll = "1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
